[project]
name = "enelvo-microservice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "enelvo>=0.15",
    "fastapi>=0.118.3",
    "redis>=6.4.0",
    "uvicorn>=0.37.0",
]
